manifest:

  remotes:
    - name: mender
      url-base: https://github.com/mendersoftware

  projects:
    - name: cjson-zephyr
      submodules: true
      remote: mender
      path: modules/lib/cjson
      revision: 35dd41f010f66bedbd34d4ec2e5595ce74faf96f
